[Timer]
  # widget collor, should be a string
  color = '#FF0000'
  # widget background color
  background_color = "#050399"
  # widget width, can be an integer or a float between 0 and 1
  width = 0.3
  # widget height, can be an integer or a float between 0 and 1
  height = 0.1
  # postion of the widget in x direction
  # can be an integer or a float between 0 and 1
  x = 0.35
  # postion of the widget in y direction
  # can be an integer or a float between 0 and 1
  # need fixing for the floating point
  y = 0.4 
  # duratoin of the cycle, should be an integer
  duration = 1500
  # number of cycles, should be a string of either a number 
  # or the "inf" string for infinite cycles
  max_cycles = "9"
  # the number of the timer starts from, should be defaulted to 0
  cycles = "0"

[Button]
  # widget collor, should be a string
  color= "#AAFF00"
  # widget background color
  background_color = "#ba4922"
  # widget width, can be an integer or a float between 0 and 1
  width = 0.3
  # widget height, can be an integer or a float between 0 and 1
  height = 10
  # postion of the widget in x direction
  # can be an integer or a float between 0 and 1
  x = 0.35
  # postion of the widget in y direction
  # can be an integer or a float between 0 and 1
  y = 0.53
  # the text displayed inside the button
  title = "my_button"
